version: '3'

networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"  # RTMP流媒体端口
      - "1980:1980"    # HTTP端口
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf  # 将本地的nginx.conf文件挂载到容器内部的nginx.conf位置
      - ./tmp/av:/tmp/av  # 录制文件存储路径
    networks:
      redis-cluster-net:
          ipv4_address: 192.168.200.223

